# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/


# @name SHOW_INDEX
GET {{baseUrl}}
###

# @name CREATE_USER
POST {{baseUrl}}
Content-Type: application/json

{
  "full_name": "Name",
  "username": "Basn",
  "password": "7659",
  "email": "232345@gmail",
  "birthday": "06/3/99",
  "status": true
}
###

# @name UPDATE_USER
PATCH {{baseUrl}}/232345@gmail.com
Content-Type:application/json

{
  "full_name": "Name",
  "username": "Bassn",
  "password": "7659",
  "email": "william5@gmail",
  "birthday": "06/3/99",
  "status": true
}
###

 # @name DELETE_USER
DELETE {{baseUrl}}/william5@gmail

###